### PR TITLE
Create documentation website and replace Formatting.jl

### PR DESCRIPTION
**Pull request by abhro**

### CODE REVIEW

**Comment by abhro** [comment]
Currently tests fail on Julia 1.3. The dependency was replaced with Format.jl, which uses the ryu algorithm, introduced in Julia 1.4. Suggest changing Julia compat rather than downgrading Format.jl compat

**Comment by abhro** [comment]
Since this updates Julia's compat entry, a bump version commit should be added, and to 0.2.0 rather than 0.1.x because it's a breaking change.

**Comment by abhro** [comment]
Using rebase+merge so that registrator can be triggered directly at the bump commit instead of the merge commit.

**Comment by giordano** [comment]
Why is that relevant?

**Comment by abhro** [comment]
If you mean the rebase, it's just so that the change can be pinned to a single delta

**Pull request merged**
